OPENAI_API_KEY="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"
COHERE_API_KEY = "am1aWz56g6Jx7oMY2SLlJPzALASAnrcXLk0Arn5s"
LANGSMITH_API_KEY = "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" # Optional, but recommended